baseURL: "https://edenz.netlify.app/"
languageCode: "en-us"
title: "Eden Zhang"
pygmentsstyle: "monokai"

# Theme settings
# theme: novela
module:
  imports:
    - path: "github.com/forestryio/hugo-theme-novela"
paginate: 6
social:
  twitter: "#"
  github: "#"
  instagram: "#"
  linkedin: "#"
  dribbble: "#"
  youtube: "#"
taxonomies:
  author: authors
